import { Header, Footer, ClientProgressProvider } from "./components";
import { Suspense } from "react";
import { Poppins } from "next/font/google";
import { Montserrat } from 'next/font/google';
import {Roboto_Slab} from "next/font/google"
import "./globals.css";

const robotoSlab =  Roboto_Slab({
  subsets: ['latin'],
  variable: '--font-roboto-slab',
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"]
})

const montserrat = Montserrat({
  subsets: ['latin'],
  variable: '--font-montserrat',
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"]
});

const poppins = Poppins({
  subsets: ["latin"],
  variable: "--font-poppins",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata = {
  title: "Custom Pack Boxes - Premium Packaging Solutions",
  description: "Generated by create next app",
  robots: "noindex, nofollow",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.variable} ${robotoSlab.variable}  antialiased`}
      >
        <Suspense>
        <ClientProgressProvider>
        <Header />
        {children}
        <Footer />
        </ClientProgressProvider>
        </Suspense>
      </body>
    </html>
  );
}
